import "../styles/globals.css";

export const metadata = {
  title: "Magda",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" href="/images/magda-icon.svg" />
      </head>
      <body>{children}</body>
    </html>
  );
}
