export const items = [
  {
    id: 1,
    image: "/images/barbara.jpeg", // Bárbara: mapa
  name: "Barbara",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Bárbara — inspirado em mim, onde a coragem e a confiança são as características que mais se destacam",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 2,
    image: "/images/angelica.jpeg", // Angélica: raio
  name: "Angelica", 
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Angélica — dedicado à minha madrinha, que com espiritualidade e afeto profundo nunca deixa meus pés saírem do chão.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 3,
    image: "/images/cristina.jpeg", // Cristina: triângulo
  name: "Cristina",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Cristina — inspirado na minha mãe, que descobriu as cores do mundo quando eu cheguei, cores que hoje usamos para pintar cada modelo com amor.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 4,
    image: "/images/magdalena.jpeg", // Magdalena: flor
  name: "Magdalena",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Magdalena — dedicado à minha vó, a razão de toda essa história, que me amou desde o primeiro segundo e que esteve presente na minha chegada assim como eu estive na sua partida.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 5,
    image: "/images/rosangela.jpeg", // Rosângela: círculo
  name: "Rosangela",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Rosângela — homenagem à minha tia, onde o amor se manifesta no cuidado com cada detalhe.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 6,
    image: "/images/leticia.jpeg", // Letícia: quadrado
  name: "Leticia",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Letícia — inspirado na minha irmã, que me mostra que nunca é tarde para criar laços e que a fé sempre nos sustenta.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 7,
    image: "/images/ester.jpeg", // Ester: coração
  name: "Ester",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Ester — dedicado à minha sobrinha, cuja doçura e paciência me lembram que nada precisa ser resolvido no grito.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 8,
    image: "/images/sara.jpeg", // Sara: estrela
  name: "Sara",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Sara — inspirado na minha sobrinha, que mostra que o mundo é movimento e ficar parado não resolve, é preciso agir.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 9,
    image: "/images/juliana.jpeg", // Juliana: lua
  name: "Juliana",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Juliana — homenagem à minha prima, que carrega uma infinitude de amor para multiplicar e sempre surpreender.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 10,
    image: "/images/natascha.jpeg", // Natascha: gota
  name: "Natascha",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Natascha — homenagem à minha prima, que sempre me mostrou que acreditar em si mesma é o que importa, porque o resto é resto.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 11,
    image: "/images/ana-luisa.jpeg", // Ana Luísa: seta
  name: "Ana-luisa",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Ana Luísa — dedicado à minha prima, que me ensinou que o simples é mágico e que um sorriso sincero vale mais que muitas coisas.",
    details: ["Material: MDF", "Peso: 10g"],
  },
  {
    id: 12,
    image: "/images/isadora.jpeg", // Isadora: boca
  name: "Isadora",
  value: 20.00,
    colors: [
      "#350b4b",
      "#0a0b0b",
      "#2e1d19",
      "#111b71",
      "#1c351f",
      "#a8350b",
      "#950b19",
      "#ac0b5b",
      "#aa950b",
    ],
    description: "Brinco Isadora — inspirado na minha prima, de onde vieram meus primeiros sorrisos sinceros, me mostrando que sorrir de volta sempre resolve.",
    details: ["Material: MDF", "Peso: 10g"],
  },
];
